version: "3"

services:
  starter-app-monolith:
    build: .
    ports:
      - "9091:9091"
    healthcheck:
      test: ["CMD", "service", "starter-app-monolith", "status"]
      interval: 1m30s
      timeout: 10s
      retries: 3
