version: "3.8"

services:
  starter-app-monolith:
    build:
      context: .
      cache_from:
        - nikolaik/python-nodejs:python3.7-nodejs10-stretch
    ports:
      - "9091:9091"
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: ["CMD", "service", "starter-app-monolith", "status"]
